name: 기타 이슈 작성 
description: 기능, 도움, 버그 외의 기타 이슈
title: '[Chore] '
labels: ['⚒️ Chore']
projects: ["Dev-FE-1/18"]
body:
  - type: textarea
    id: bug-description
    attributes:
      label: 📄 설명
      description: 새로운 기능에 대한 설명을 작성해 주세요.
      placeholder: 자세하게 작성하기!
    validations:
      required: false
  - type: textarea
    id: bug-more
    attributes:
      label: 📝 메모
      description: 더 하고 싶은 말이 있다면 작성해 주세요.
    validations:
      required: false
