name: Set Issue Status

on:
  issues:
    types: [opened]

jobs:
  set-status:
    runs-on: ubuntu-latest
    steps:
      - name: Set issue status to Todo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_ID: ${{ github.event.issue.node_id }}
          PROJECT_ID: <your-project-id>
          STATUS_FIELD_ID: <your-status-field-id>
          TODO_OPTION_ID: <your-todo-option-id>
        run: |
          query='mutation($project:ID!, $item:ID!, $status_field:ID!, $status_value:String!) {
            updateProjectV2ItemFieldValue(
              input: {
                projectId: $project
                itemId: $item
                fieldId: $status_field
                value: { 
                  singleSelectOptionId: $status_value
                }
              }
            ) {
              projectV2Item {
                id
              }
            }
          }'
          
          gh api graphql -f query="${query}" -f project="${PROJECT_ID}" -f item="${ISSUE_ID}" -f status_field="${STATUS_FIELD_ID}" -f status_value="${TODO_OPTION_ID}"
